# Generated by Django 4.0.7 on 2022-08-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID пользователя в TG')),
                ('name', models.CharField(max_length=255, verbose_name='Login пользователя в TG')),
                ('start_raiting', models.IntegerField(verbose_name='Начальный рейтинг')),
                ('end_raiting', models.IntegerField(verbose_name='Желаемый рейтинг')),
                ('decency', models.IntegerField(verbose_name='Порядочность')),
                ('lvl_trophies', models.IntegerField(verbose_name='Уровень трофеев')),
                ('duo', models.BooleanField(default=False, verbose_name='Дуо')),
                ('price', models.FloatField(verbose_name='Цена заказа')),
                ('is_completed', models.BooleanField(verbose_name='Заказ выполнен')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('desc', models.TextField(verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-id', 'name'],
            },
        ),
    ]
